### ISSUE TITLE
Cannot find module 'bn-ng-idle' or its corresponding type declarations. Version 2.0.3 issue with bn-ng-idle

### ISSUE THREAD

**Issue by angelaki** [bearnithi/bn-ng-idle#48]
Importing the latest release `import { BnNgIdleService } from 'bn-ng-idle';` brings up on error on starting. Is this a known problem?

**Comment by bearnithi** [comment]
Hi @angelaki , could you please share the screenshot of the error that you are facing?

**Comment by angelaki** [comment]
Yeah, sure:

![image](https://user-images.githubusercontent.com/38611461/183444913-8738bba4-f50d-4047-bfef-640e6a9f0a05.png)

**Comment by bearnithi** [comment]
@angelaki , could you please update the version to 2.0.4 now? there was an issue with the build in the 2.0.3. it's fixed now. please check and let me know if you need any further help.

**Comment by angelaki** [comment]
Works like a charm, thank you so much! :)
